#+AUTHOR: Daniele Santoro
#+TITLE: Ajax polling
#+DATE: 27/11/2015

* Introduction
  - Code and documentation are present at this link: https://github.com/acca/assignment6.
  - Demo deployment available here: http://PUBLIC_IP_ADDRESS:8080/assignment7
  
  This application demonstrates a basic utilization of AJAX technology.

  I've deployed:
  - *The Servlet*: Implements =HttpServlet= which manages the clients request efficiently using threads.
  - *The CSS file*: Control styling of the web page.
  - *The Javascript file*: Downloaded and then executed from the client browser.
  - *The JSP page*: Static HTML page the browser's client access to.

* Implementation

  Specific functionality of each class/files are described below:

  - *AjaxServlet.java*: It manages the asynchronous requests coming to the web-server (tomcat) from the client requesting an update. It return a text payload. The following parameters are checked in the HTTP request:
   - =op=: Operation to be performed. Can be =reload= to reload the background color.

  - *client.js*: Contains the Javascript code which the client run. It includes creation of the =XMLHttpRequest= object and its asynchronous call towards the server endpoint in order to request an updated random color which is finally used by the browser to set the background of the HTML page.

  - *style.css*: Style for the index.jsp page.

  - *index.jsp*: Just a JSP page which redirect the user to the Servlet URL.
* Deployment
  The repository contains a /Maven/ based project developed using Eclipse which can be deployed following the below instructions.
** Deploy & Run
   1) Download the repository using git:
      #+BEGIN_EXAMPLE
      git clone https://github.com/acca/assignment7.git
      #+END_EXAMPLE
   2) Move into the project main folder
      #+BEGIN_EXAMPLE
      cd ./assignment7
      #+END_EXAMPLE
   3) Build the web application
      #+BEGIN_EXAMPLE
      mvn install
      #+END_EXAMPLE
   4) Move the generated =target/assignment7.war= file into your Tomcat =webapps= folder
      #+BEGIN_EXAMPLE
      cp target/assignment7.war $TOMCAT_HOME/webapps
      #+END_EXAMPLE
   5) Have a nice time with AJAX polling update from client to server:
      http://localhost:8080/assignment7

** Screen-shots
   I think that a demo is better than many screen-shots, for this reason I've deployed the application on a public tomcat server available at the following address:

   http://PUBLIC_IP_ADDRESS:8080/assignment7

   /(IP address will be shared only in the mail to the teacher for security reasons)/
